name: compile and publish client

on:
  workflow_dispatch:
    branches:
      - '*'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/build.yml'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Gradle Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Chmod Gradle
        run: chmod +x gradlew
      - name: Importing secrets
        run: |
          echo "${{ secrets.prop }}" | base64 -d > local.properties
          echo "${{ secrets.keystore }}" | base64 -d > keystore.properties
      - name: Setup
        run: |
          export TERM=linux
          git submodule init && git submodule update --init --recursive --depth=1
          scripts/./setup.sh
      - name: Build
        run: |
          export token=$(echo "${{ secrets.token }}" | base64 -d)
          export chatid=$(echo "${{ secrets.chatid }}" | base64 -d)
          export chatid_chlog=$(echo "${{ secrets.chatid_chlog }}" | base64 -d)
          export isstable=$(echo "${{ secrets.isstable }}" | base64 -d)
          export chatid_release=$(echo "${{ secrets.chatid_release }}" | base64 -d)
          export commit="${{ github.event.head_commit.message }}"
          export commit_author="${{ github.actor }}"
          export commit_sha="${{ github.sha }}"
          export run_num="${{ github.run_number }}"
          bash build.sh
